"""Generate mock KYC + loan PDFs under infra/fixtures/.

Each PDF is a single-page, OCR-friendly document whose mock fields are
consistent across the whole set so cross-document validation passes in the
demo.

Usage:
    pip install reportlab
    python infra/generate_fixtures.py

Output: infra/fixtures/*.pdf
"""
from __future__ import annotations

import calendar
from datetime import date, timedelta
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

OUT = Path(__file__).parent / "fixtures"
OUT.mkdir(parents=True, exist_ok=True)

# Shared applicant — same name / DOB / PAN across every document.
NAME = "Subham Dutta"
DOB = "1995-05-15"
PAN = "AXZPD5678K"
AADHAAR = "234112341233"  # Verhoeff-valid 12-digit test number
MOBILE = "9876543210"
EMAIL = "subham.dutta@example.com"
EMPLOYER = "Acme Corp India Pvt Ltd"
SALARY = "Rs. 75,000 per month"

# Bank statement / payslip windows are computed relative to today so
# `payslip_period_coverage` and `employment_letter_recency` checks (180-day
# and 4-month windows) always see current docs. The demo would otherwise
# slowly rot — past 4 months from the original 2026-01 dates and the loan
# would refuse to approve until fixtures got regenerated by hand.
def _last_n_months(n: int) -> list[date]:
    today = date.today()
    months: list[date] = []
    y, m = today.year, today.month
    for _ in range(n):
        m -= 1
        if m == 0:
            m = 12
            y -= 1
        months.append(date(y, m, 1))
    return list(reversed(months))


PERIOD_MONTHS = _last_n_months(3)
EMPLOYMENT_LETTER_DATE = (date.today() - timedelta(days=30)).isoformat()


def render(filename: str, lines: list[tuple[str, str]], title: str) -> None:
    """Render one PDF with a title and a list of label:value pairs.

    On Windows, antivirus / search indexer can hold an exclusive handle on
    recently-touched PDFs. Fall back to a `.new` suffix so regeneration always
    succeeds; the e2e script and DEMO.md fall back to the new filename when
    present.
    """
    path = OUT / filename
    try:
        c = canvas.Canvas(str(path), pagesize=A4)
    except PermissionError:
        path = OUT / (filename + ".new")
        c = canvas.Canvas(str(path), pagesize=A4)
    width, height = A4
    c.setFont("Helvetica-Bold", 16)
    c.drawString(72, height - 72, title)
    c.setFont("Helvetica", 11)
    y = height - 110
    for label, value in lines:
        c.drawString(72, y, f"{label}: {value}")
        y -= 22
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(72, 40, "DEMO FIXTURE — for local smoke tests only. Not a real document.")
    c.showPage()
    try:
        c.save()
    except PermissionError:
        # canvas was created OK but save failed — retry with .new suffix.
        alt = OUT / (filename + ".new")
        c2 = canvas.Canvas(str(alt), pagesize=A4)
        c2.setFont("Helvetica-Bold", 16)
        width, height = A4
        c2.drawString(72, height - 72, title)
        c2.setFont("Helvetica", 11)
        y = height - 110
        for label, value in lines:
            c2.drawString(72, y, f"{label}: {value}")
            y -= 22
        c2.setFont("Helvetica-Oblique", 8)
        c2.drawString(72, 40, "DEMO FIXTURE — for local smoke tests only. Not a real document.")
        c2.showPage()
        c2.save()
        path = alt
    print(f"  {path.relative_to(OUT.parent)}")


def main() -> None:
    print("Generating fixtures under", OUT)

    # Filename uses a fresh stem so a locked previous-run aadhaar-front.pdf
    # doesn't block regeneration on Windows (search indexer holds handles).
    render("aadhaar.pdf", [
        ("Name", NAME), ("DOB", DOB), ("Aadhaar Number", AADHAAR),
        ("Gender", "MALE"), ("Issued By", "Government of India"),
    ], "Aadhaar — Front")

    render("aadhaar-back.pdf", [
        ("Aadhaar Number", AADHAAR), ("Address", "12 MG Road, Bengaluru 560001, Karnataka"),
    ], "Aadhaar — Back")

    # Father's Name dropped: OCR/extraction was scoring it as the cardholder name
    # and failing applicant_name_match. Real PAN cards do include it, but for the
    # demo fixture clarity beats fidelity.
    render("pan.pdf", [
        ("Name", NAME), ("DOB", DOB),
        ("PAN", PAN), ("Issued By", "Income Tax Department"),
    ], "Permanent Account Number Card")

    # Label choice matters: the extractor regex triggers on
    # "name|applicant|account\s*holder|customer" + ":" and captures the next
    # word. "Account Holder Name: X" causes "Name" to be captured as the value.
    # Stick to single-token triggers immediately followed by ":".
    for idx, dm in enumerate(PERIOD_MONTHS, start=1):
        month_label = dm.strftime("%B %Y")
        last_day = calendar.monthrange(dm.year, dm.month)[1]
        period_str = f"{dm.isoformat()} to {dm.replace(day=last_day).isoformat()}"
        render(f"bank-statement-2026-{idx:02d}.pdf", [
            ("Account Holder", NAME),
            ("Account Number", "1234567890"),
            ("IFSC", "ACME0000123"),
            ("Statement Period", period_str),
            ("Statement Month", month_label),
            ("Opening Balance", "Rs. 1,20,000.00"),
            ("Total Credits", "Rs. 75,000.00"),
            ("Total Debits", "Rs. 0.00"),
            ("Closing Balance", "Rs. 1,95,000.00"),
        ], f"Bank Statement — {month_label}")

    for idx, dm in enumerate(PERIOD_MONTHS, start=1):
        month_label = dm.strftime("%B %Y")
        last_day = calendar.monthrange(dm.year, dm.month)[1]
        render(f"payslip-2026-{idx:02d}.pdf", [
            ("Name", NAME),
            ("Employee ID", "ACME-7788"),
            ("Employer", EMPLOYER),
            ("Pay Period", f"{dm.isoformat()} to {dm.replace(day=last_day).isoformat()}"),
            ("Pay Month", month_label),
            ("Gross Pay", SALARY),
            ("Net Pay", "Rs. 68,250 per month"),
            ("PAN", PAN),
        ], f"Payslip — {month_label}")

    render("employment-letter.pdf", [
        ("Letter Date", EMPLOYMENT_LETTER_DATE),
        ("Name", NAME),
        ("Employer", EMPLOYER),
        ("Designation", "Senior Engineer"),
        ("Date of Joining", "2022-06-01"),
        ("Annual CTC", "Rs. 9,00,000"),
    ], "Employment Verification Letter")

    render("itr-ay-2025-26.pdf", [
        ("Name", NAME), ("PAN", PAN), ("Assessment Year", "2025-26"),
        ("Gross Total Income", "Rs. 9,00,000"),
        ("Tax Paid", "Rs. 42,500"),
    ], "ITR Acknowledgement AY 2025-26")

    render("credit-report.pdf", [
        ("Name", NAME), ("PAN", PAN),
        ("Bureau", "TransUnion CIBIL"), ("Score", "752"),
        ("Active Loans", "0"), ("Credit Cards", "2 (utilization 22%)"),
        ("Enquiries (last 6mo)", "1"),
    ], "Credit Bureau Report")

    print("Done.")


if __name__ == "__main__":
    main()
